# Resources settings
source:      .
destination:      ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
timezone:    Asia/Hongkong
gems:        []
highlighter:     rouge

# Site settings
email: 782652987@qq.com
author: Jing He
owner_name: Jing He

#Server
url: https://github.com/six-walnut
github: https://github.com/six-walnut/
baseurl: ""
dnsPrefetch: "on"
#dnsPrefetch: "off" if don't want use dns-prefetch
dns:
      - "//dns18.hichina.com"
      - "//dns17.hichina.com"
      
#Github announce Settings
github_username: six-walnut
github_repo: six-walnut.github.io
github_label: announcement

#Page settings
future: true
show_drafts: nil
lsi: true
published: false
safe: false
permalink: /:year/:month/:day/:title/
markdown: kramdown

#Navbar setting
#If show the 'download' item on the navbar
showdownload: true

#Pagination setting
#Testing, not opening
paginatenum: 2
 
exclude: ['README.md','Manifest.md']
include: ['robots.txt','404.html','.htaccess']

# Description
description: "只为博客而生，也因为博客而存在。Not only for the existence of the blog, but also because of the existence of the blog."

# Keywords
keywords:
        - "git"
        - "bootstrap"
        - "blog"
        - "joytou"
        - "markdown"
        - "jekyll"
        - "博客"
        - "博客模板"
        - "jekyll主题"
        - "jekyll theme"
        - "liquid"
        - "静态"
        - "响应式"
        - "Coding"
        - "gitee"
        - "github"
        

#Others

#ChangYan
changyan:
  appid: "cys9CkC150"
  appconf: "prod_6c14cfe1b9706846e412ddac9bcdb06822"
  
#Formspree
formspree:
  email_prefix: "782652987"
  email_suffix: "qq.com"
